/' http://plantuml.com/class-diagram '/ 

@startuml CG-N4

title Diagrama de Classes
footer Grupo GCG - [[http://gcg.inf.furb.br]]

!include ../../CG-N2/docs/umlClasses.wsd

Mundo : - void Metodos_CG-N4()


@enduml
